export const json = {
  calendarContainer: { boxSizing: 'border-box' },
  calendarContainer__dayPickerContainer_after: {
    content: "''",
    display: 'block',
    clear: 'both',
  },
  calendarContainer__monthsList_after: {
    content: "''",
    display: 'block',
    clear: 'both',
  },
  calendarContainer__daysOfWeek_after: {
    content: "''",
    display: 'block',
    clear: 'both',
  },
  calendarContainer__heading: {
    height: '42px',
    fontWeight: 'bold',
    marginBottom: '10px',
  },
  calendarContainer__heading___button: {
    borderRadius: '3px',
    background: 'none',
    margin: '5px 0',
    border: '1px solid #F7F7F7',
    textAlign: 'center',
    lineHeight: '30px',
    width: '36px',
    height: '32px',
    cursor: 'pointer',
  },
  calendarContainer__heading___button_hover: { backgroundColor: '#f2f2f2' },
  calendarContainer__heading___span: { lineHeight: '35px' },
  calendarContainer__heading_svg: { width: '10px' },
  calendarContainer__heading__prev: { float: 'right' },
  calendarContainer__heading__next: { float: 'left' },
  calendarContainer__heading__title: {
    lineHeight: '32px',
    width: '120px',
    height: '32px',
    fontSize: '1em',
    margin: '5px 0',
    border: '1px solid #F7F7F7',
    textAlign: 'center',
    display: 'inline-block',
    fontWeight: 'normal',
  },
  calendarContainer__dayWrapper: {
    padding: '5',
    float: 'right',
    width: '14.28571429%',
  },
  calendarContainer__dayWrapper_button: {
    border: 'none',
    background: 'none',
    outline: 'none',
    width: '100%',
    height: '36px',
    borderRadius: '3px',
    cursor: 'pointer',
  },
  calendarContainer__dayWrapper_button_hover: { backgroundColor: '#eeeeff' },
  calendarContainer__dayWrapper_button_disabled: {
    color: '#aaa',
    cursor: 'not-allowed',
    backgroundColor: '#ebebeb',
  },
  calendarContainer__dayWrapper_button_selected: {
    backgroundColor: '#337ab7',
    color: '#ffffff',
  },
  calendarContainer__dayWrapper_not__currentMonth__button: { opacity: '.5' },
  calendarContainer__daysOfWeek: {
    borderBottom: '1px solid #EEE',
    marginBottom: '5px',
    paddingBottom: '5px',
    display: 'flex',
    width: '100%',
  },
  calendarContainer__daysOfWeek___div: {
    flexGrow: '1',
    justifyContent: 'space-between',
  },
  calendarContainer__monthsList: { clear: 'both', width: '100%' },
  calendarContainer__monthsList_button: {
    width: '33.33333332%',
    height: '25%',
    float: 'right',
    border: '1px solid #F9F9F9',
    outline: 'none',
    fontSize: '1em',
    background: '#fff',
    padding: '10px 0',
    cursor: 'pointer',
  },
  calendarContainer__monthsList_button_hover: {
    background: '#eeeeee',
    cursor: 'pointer',
  },
  calendarContainer__selected_button: {
    backgroundColor: '#337ab7',
    color: '#ffffff',
  },
  calendarContainer__selected_button_hover: {
    backgroundColor: '#337ab7',
    color: '#ffffff',
  },
  calendarContainer__selected_button_active: {
    backgroundColor: '#337ab7',
    color: '#ffffff',
  },
  calendarContainer__selected_button_focus: {
    backgroundColor: '#337ab7',
    color: '#ffffff',
  },
}
