name: Deploy to production server

on: 
  push:
    branches:
      - deploy-preparation
jobs:
  build-front:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Prepare deploy folder
        run: |
          mkdir to_be_deployed
          mv dist to_be_deployed
          cp -r deploy/* to_be_deployed

      - name: Configure git
        run: |
          git config --global user.name "Sharif-League-of-Coders"
          git config --global user.emal "Sharif-League-of-Coders@users.noreply.github.com"

      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: to_be_deployed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build"

  deploy-front:
    needs: build-front
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }}
          script: |
            cd ${{ secrets.PRODUCTION_TARGET_PATH }}
            git pull
            ls
            docker-compose build
            docker-compose up -d
